targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
          addTypename: true
          addTypenameExcludedPaths: 
            - subscription